Update redirects-transition.conf
fecgov/fec-proxy pull request #276
Opened 2021-07-13 14:37 UTC by kathycarothers

I have updated the presidential matching funds submission pages from transitions to wagtail. The need to be reviewed and deployed.

2021-07-13 15:13 UTC, dorothyyeager approved these changes
This looks great to me Kathy. Thank you so much for working on this particular project.

2021-07-17 19:31 UTC, bmathesonFEC commented
I just made a commit to Kathy's branch off of dev. Added a few previously missed redirects and new redirects identified in the 7/13 transition inventory meeting.

2021-07-20 16:14 UTC, patphongs requested changes
@kathycarothers Just one minor change:

2021-07-20 16:14 UTC, patphongs commented on redirects-transition.conf
> +xrewrite ^/law/cfr/ej_citation.shtml https://www.fec.gov/legal-resources/regulations/explanations-and-justifications/explanations-and-justifications-citation-index/ redirect;
@kathycarothers Please change from `xrewrite` to `rewrite` at the beginning of this line.

2021-07-20 16:19 UTC, patphongs approved these changes
Looks good, thanks @kathycarothers!

2021-07-20 16:19 UTC, merged